<?php
use Zend\Session\Container;
echo $this->doctype();
$basePath = $this->basePath();
$sessionContainer = new Container('authentication');
$menuHtml = $sessionContainer->menu_html; //print_r($menuHtml); exit;
$logoutUrl = $sessionContainer->logout_url;
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('Cloud Services'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>
        <!-- GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <link href="<?=$basePath;?>/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$basePath;?>/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$basePath;?>/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN THEME STYLES -->
        <link href="<?=$basePath;?>/assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
        <link href="<?=$basePath;?>/assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$basePath;?>/assets/admin/layoutcs/css/layout.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$basePath;?>/assets/admin/layoutcs/css/themes/csblue.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?=$basePath;?>/assets/admin/layoutcs/css/custom.css" rel="stylesheet" type="text/css"/>
        <!-- END THEME STYLES -->
        
        <script src="<?=$basePath;?>/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="<?=$basePath;?>/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
        <!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
        <script src="<?=$basePath;?>/assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="<?=$basePath;?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?=$basePath;?>/assets/global/scripts/metronic.js" type="text/javascript"></script>
        <script src="<?=$basePath;?>/assets/admin/layoutcs/scripts/layout.js" type="text/javascript"></script>
        <script>
        jQuery(document).ready(function(){
            Layout.init(); // init layout
            var pathname = window.location.pathname;
            pathname = pathname.replace(new RegExp('/', 'g'), '_');
            var classActive = 'class_'+pathname.replace('.', '_');
            var activeObject = $('.'+classActive);
            if(activeObject.length > 0){
                activeObject = $(activeObject[0]);
                activeObject.addClass('active');
                for(var runTmp=0; runTmp<10; runTmp++){
                    activeObject = activeObject.parent();
                    var tagNameTmp = activeObject.prop('tagName');
                    //console.log(tagNameTmp);
                    if(tagNameTmp == 'DIV'){ break; }
                    if(tagNameTmp == 'LI'){
                        activeObject.addClass('active open');
                        activeObject.find('.arrow').addClass('active open');
                    }
                }                
            }
        });
        </script>
    </head>
    <body class="page-header-fixed page-quick-sidebar-over-content page-sidebar-closed-hide-logo page-container-bg-solid page-sidebar-closed">
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
                <!-- BEGIN HEADER INNER -->
                <div class="page-header-inner">
                        <!-- BEGIN LOGO -->
                        <div class="page-logo">
                            <a href="index.html">
                            <img src="<?=$basePath;?>/assets/admin/layout/img/logo.png" alt="logo" class="logo-default-s" style="margin:16px 16px 0;"/>
                            </a>
                            <div class="menu-toggler sidebar-toggler hide">
                            </div>
                        </div>
                        <!-- END LOGO -->
                        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                        </a>
                        <!-- END RESPONSIVE MENU TOGGLER -->
                        <!-- BEGIN TOP NAVIGATION MENU -->
                        <div class="top-menu">
                                <ul class="nav navbar-nav pull-right">
                                        <!-- BEGIN NOTIFICATION DROPDOWN -->
                                        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                                        <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                                <i class="icon-bell"></i>
                                                <span class="badge badge-default">
                                                7 </span>
                                                </a>
                                                <ul class="dropdown-menu">
                                                        <li class="external">
                                                                <h3><span class="bold">12 pending</span> notifications</h3>
                                                                <a href="extra_profile.html">view all</a>
                                                        </li>
                                                        <li>
                                                                <ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
                                                                        <li>
                                                                                <a href="javascript:;">
                                                                                <span class="time">just now</span>
                                                                                <span class="details">
                                                                                <span class="label label-sm label-icon label-success">
                                                                                <i class="fa fa-plus"></i>
                                                                                </span>
                                                                                New user registered. </span>
                                                                                </a>
                                                                        </li>
                                                                </ul>
                                                        </li>
                                                </ul>
                                        </li>
                                        <!-- END NOTIFICATION DROPDOWN -->
                                        <!-- BEGIN USER LOGIN DROPDOWN -->
                                        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                                        <li class="dropdown dropdown-user">
                                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                                <img alt="" class="img-circle" src="<?=$basePath;?>/assets/admin/layout/img/avatar3_small.jpg"/>
                                                <span class="username username-hide-on-mobile">
                                                Nick </span>
                                                <i class="fa fa-angle-down"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-menu-default">
                                                        <li>
                                                                <a href="extra_profile.html">
                                                                <i class="icon-user"></i> My Profile </a>
                                                        </li>
                                                        <li class="divider">
                                                        </li>
                                                        <li>
                                                                <a href="extra_lock.html">
                                                                <i class="icon-lock"></i> Lock Screen </a>
                                                        </li>
                                                        <li>
                                                                <a href="<?=$logoutUrl;?>">
                                                                <i class="icon-key"></i> Log Out </a>
                                                        </li>
                                                </ul>
                                        </li>
                                        <!-- END USER LOGIN DROPDOWN -->
                                </ul>
                        </div>
                        <!-- END TOP NAVIGATION MENU -->
                </div>
                <!-- END HEADER INNER -->
        </div>
        <!-- END HEADER -->
        <div class="clearfix">
        </div>
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar-wrapper">
                    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                    <div class="page-sidebar navbar-collapse collapse">
                            <!-- BEGIN SIDEBAR MENU -->
                            <ul class="page-sidebar-menu page-sidebar-menu-closed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                                    <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                                    <li class="sidebar-toggler-wrapper">
                                            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                                            <div class="sidebar-toggler">
                                            </div>
                                            <!-- END SIDEBAR TOGGLER BUTTON -->
                                    </li>
                                    <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
                                    <li class="sidebar-search-wrapper">
                                            <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                                            <!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
                                            <!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
                                            <form class="sidebar-search " action="extra_search.html" method="POST">
                                                    <a href="javascript:;" class="remove">
                                                    <i class="icon-close"></i>
                                                    </a>
                                                    <div class="input-group">
                                                            <input type="text" class="form-control" placeholder="Search...">
                                                            <span class="input-group-btn">
                                                            <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
                                                            </span>
                                                    </div>
                                            </form>
                                            <!-- END RESPONSIVE QUICK SEARCH FORM -->
                                    </li>
                                    <?php echo $menuHtml; ?>
                            </ul>
                            <!-- END SIDEBAR MENU -->
                    </div>
            </div>
            <!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-content">
                <?php echo $this->content; ?>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
                <div class="page-footer-inner">
                    2015 &copy; Cloud services.
                </div>
                <div class="scroll-to-top">
                    <i class="icon-arrow-up"></i>
                </div>
        </div>
        <!-- END FOOTER -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
