<?php $basePath = $this->basePath(); ?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>CLoud services | Login</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="<?=$basePath;?>/assets/global/plugins/select2/select2.css" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/admin/pages/css/login3.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="<?=$basePath;?>/assets/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="<?=$basePath;?>/assets/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="<?=$basePath;?>/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN LOGO -->
<!--
<div class="logo">
	<a href="index.html">
	<img src="<?php /*echo $basePath;*/ ?>/assets/admin/layout4/img/logo-big.png" alt=""/>
	</a>
</div>
-->
<div class="logo" style="margin-bottom: 20px;">
<b style="color:#FFF; font-size:24px; font-family: 'Tahoma', Times, serif;font-weight: 100;">CLOUD SERVICES</b>
<b style="color:#D11D43; font-size:24px; font-family: 'Tahoma', Times, serif;font-weight: 100;">CENTER</b>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">
    <?php echo $this->content; ?>
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
	 2015 &copy; Cloud services.
</div>
<!-- END COPYRIGHT -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="<?=$basePath;?>/assets/global/plugins/respond.min.js"></script>
<script src="<?=$basePath;?>/assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="<?=$basePath;?>/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$basePath;?>/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?=$basePath;?>/assets/global/plugins/select2/select2.min.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$basePath;?>/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
<script src="<?=$basePath;?>/assets/admin/pages/scripts/login.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {     
    Metronic.init(); // init metronic core components
    Layout.init(); // init current layout
    Login.init();
    Demo.init();
});
</script>
<?php echo $this->inlineScript() ?>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>